assignment_id: 00-Dev_Environment
title: Development Environment & Workflow Setup
course: 4543-5993-Spatial-Data
type: onboarding
points: '0'
graded: false
estimated_time: 60-90 minutes
objectives:
- Set up a consistent development environment
- Learn the course workflow for notebooks and GitHub
- Successfully launch and use GitHub Codespaces
- Run and save a Jupyter notebook
- Commit and push changes to GitHub
tools:
  required:
  - GitHub
  - GitHub Codespaces
  - VS Code
  - Jupyter Notebooks
  optional:
  - Local VS Code
  - Google Colab
deliverables:
- Working GitHub repository
- Successfully launched Codespace
- At least one committed Jupyter notebook
- Completed checklist
submission:
  type: completion
  method: instructor_verification
  notes: 'This assignment is required but not graded. Students must complete this
    setup before continuing.

    '
policies:
  late: not_applicable
  resubmission: allowed
  collaboration: allowed
notes_for_students: 'This setup will be reused throughout the course. Investing time
  here will save you time later.

  '
notes_for_instructor: 'This assignment establishes a consistent environment and reduces
  downstream debugging issues.

  '
due: 2026-02-08 23:59
