title: Assignment 00
description: Setup Git and Slack
slug: git-slack-setup
type: assignment
due_date: 2026-01-28
points: 100
released: 2026-01-24
late_penalty: 10% per day
submission: none
visible: true